# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'repos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for repos
	pod ‘Alamofire’
	pod ‘Kingfisher’
	pod ‘RxSwift’
	pod ‘RxCocoa’
	pod 'OAuthSwift', '~> 1.2.0'
end
